# Generated by Django 4.2.13 on 2024-06-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('frase_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('lvl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hero', models.CharField(max_length=100)),
                ('image_back', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('defeat', models.IntegerField()),
                ('fases', models.IntegerField()),
                ('bottles', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_enemy', models.CharField(max_length=100)),
                ('image_back', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('defeat', models.IntegerField()),
                ('fases', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('money', models.IntegerField()),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.frases')),
            ],
        ),
    ]
