# Generated by Django 4.2.13 on 2024-06-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_enemy', models.CharField(max_length=100)),
                ('image_back', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('min_damage', models.IntegerField()),
                ('defeat', models.IntegerField()),
                ('min_defeat', models.IntegerField()),
                ('fases', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('min_enemy_hp', models.IntegerField()),
                ('max_enemy_hp', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('money', models.IntegerField()),
                ('min_money', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('min_exp', models.IntegerField()),
                ('hero_defeat_debaf', models.IntegerField()),
                ('hero_damage_debaf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='image_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_hero', models.CharField(max_length=100)),
                ('image_back', models.CharField(max_length=100)),
                ('damage', models.IntegerField()),
                ('defeat', models.IntegerField()),
                ('fases', models.IntegerField()),
                ('bottles', models.IntegerField()),
                ('bottle_hp', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('max_hp', models.IntegerField()),
                ('lvl', models.IntegerField()),
                ('lvl_points', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('exp_to_next_lvl', models.IntegerField()),
                ('enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.enemy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Frases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('frase_text', models.TextField()),
                ('enemy_hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enemy')),
            ],
        ),
    ]
