# Generated by Django 4.2.13 on 2024-06-05 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='frase',
        ),
        migrations.AddField(
            model_name='frases',
            name='enemy_hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.enemy'),
        ),
    ]
