# Generated by Django 4.2.13 on 2024-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='gold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
